package model;
// Generated Nov 27, 2017 6:29:00 PM by Hibernate Tools 4.3.1



/**
 * EmployeeAuth generated by hbm2java
 */
public class EmployeeAuth  implements java.io.Serializable {


     private Integer authId;
     private Employees employees;
     private String username;
     private String password;

    public EmployeeAuth() {
    }

    public EmployeeAuth(Employees employees, String username, String password) {
       this.employees = employees;
       this.username = username;
       this.password = password;
    }
   
    public Integer getAuthId() {
        return this.authId;
    }
    
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


