package model;
// Generated Nov 27, 2017 8:07:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Requests generated by hbm2java
 */
public class Requests  implements java.io.Serializable {


     private Integer requestId;
     private Date timestamp;
     private Employees employees;
     private Date startDate;
     private Date returnDate;
     private String reason;
     private int daysRequested;

    public Requests() {
    }

	
    public Requests(Employees employees, Date startDate, Date returnDate, int daysRequested) {
        this.employees = employees;
        this.startDate = startDate;
        this.returnDate = returnDate;
        this.daysRequested = daysRequested;
    }
    public Requests(Employees employees, Date startDate, Date returnDate, String reason, int daysRequested) {
       this.employees = employees;
       this.startDate = startDate;
       this.returnDate = returnDate;
       this.reason = reason;
       this.daysRequested = daysRequested;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public int getDaysRequested() {
        return this.daysRequested;
    }
    
    public void setDaysRequested(int daysRequested) {
        this.daysRequested = daysRequested;
    }




}


